### ISSUE TITLE
Audio jack does not work

### ISSUE THREAD

**Issue by ADeadTrousers** [ADeadTrousers/android_device_Unihertz_Atom_XL#2]
Connecting headphones to audio jack you can hear the slight clicking noise they make on contact but nothing else happens.
In stock ROM you could see an icon in the status bar but not in Lineage.

**Comment by ADeadTrousers** [comment]
This is starting to bug me pretty much.
So this is the next thing on my to-do-list. 
But for that I first need a `adb -d logcat > audiojack.txt` from the moment someon plugs in some headphones into the audio jack.
My believe is that there must be some events triggered by a internal "service" that is not started during booting of the phone. I have serveral candidates found inside the stock rom but I only want to activate what is really needed and nothing more (bloatware).

**Comment by SepticFuddy** [comment]
[audiojack.txt](https://github.com/ADeadTrousers/android_device_Unihertz_Atom_XL/files/5521176/audiojack.txt)
I rebooted, plugged and unplugged the jack, then ran the logcat command.

As a bonus, you get a little peek into my music collection. Not exactly what the DRM Service thing is all about, since they're CD rips...

**Comment by ADeadTrousers** [comment]
Thanks, but the log is a little bit too big for me to find anything useful. Sorry. Your music taste is great though ;)
Can you please try to clear the logcat first (`adb logcat -c all`), then start the log, plug in and unplug your headphones and finally stop the log. Also roughly remember the timestamp when you plugged in the headphones (the secondes) just in case.

**Comment by SepticFuddy** [comment]
[audiojack.txt](https://github.com/ADeadTrousers/android_device_Unihertz_Atom_XL/files/5541762/audiojack.txt)
Alright this one's much cleaner. Looks like I plug in at 47 sec and unplug at 49 sec.

**Comment by ADeadTrousers** [comment]
WiredAccessoryManager is a service in framework but it doesn't seem to detect the hardware.
I found a guide that describes how to add an audio device to android:
https://wiki.st.com/stm32mpu/wiki/How_to_change_audio_device_for_Android
But that seems a little bit excessive. At least this is a possibility.
Another way would be to try out the various AUDIO_* variables inside BoardConfig.mk but I need the correct settings, best from another mt6771 device.

**Comment by ADeadTrousers** [comment]
Fixed with 24ad9ff230a7a50213128b589405a421a663c65d
The icon still doesn't show up in the status bar but at least I once more hear something from my headphones.
