### ISSUE TITLE
Notification LED not working

### ISSUE THREAD

**Issue by ADeadTrousers** [ADeadTrousers/android_device_Unihertz_Atom_XL#6]
The notification LED does not work.
I found various settings (product build.prop, ueventd,rc) mentioning the three led colours and have already copied them but it's still not working. So anyone who knows how to get it to work is much appreciated.

**Comment by SepticFuddy** [comment]
Anything I might be able to help with from stock on this? I was considering migrating to your latest build with the other issues fixed now.

**Comment by ADeadTrousers** [comment]
Thanks, but I'm quite confident that I already have everything.
As I recently learned with the audio jack and tethering many things can be "fixed" with overlays.
I only need to find the correct flags for the MT6771/MT65XX-LED:
https://review.lineageos.org/c/LineageOS/android_device_sony_xz2c/+/275672/3

**Comment by ADeadTrousers** [comment]
I'm on the right track it seems.
The notification LED is working, but not as expected. I seem to have gotten the wrong bits.

**Comment by ADeadTrousers** [comment]
The correct bit set is 75. c6f0c6170e2353f6f92391f88f0a1fdf68c70398
